export const slices = [
  {
    name: "C",
    minor: "Am",
    keyName: "C Major\n\nA Minor",
    angle: 0,
    color: "#e74c3c",
  },
  {
    name: "G",
    minor: "Em",
    keyName: "G Major\n\nE Minor",
    angle: 30,
    color: "#e67e22",
  },
  {
    name: "D",
    minor: "Bm",
    keyName: "D Major\n\nB Minor",
    angle: 60,
    color: "#f1c40f",
  },
  {
    name: "A",
    minor: "F♯m",
    keyName: "A Major\n\nF# Minor",
    angle: 90,
    color: "#2ecc71",
  },
  {
    name: "E",
    minor: "C♯m",
    keyName: "E Major\n\nC# Minor",
    angle: 120,
    color: "#1abc9c",
  },
  {
    name: "B",
    minor: "G♯m",
    keyName: "B Major\n\nG# Minor",
    angle: 150,
    color: "#3498db",
  },
  {
    name: "F♯",
    minor: "D♯m",
    keyName: "F# Major\n\nD# Minor",
    angle: 180,
    color: "#c786e1",
  },
  {
    name: "D♭",
    minor: "B♭m",
    keyName: "D♭ Major\n\nB♭ Minor",
    angle: 210,
    color: "#8e44ad",
  },
  {
    name: "A♭",
    minor: "Fm",
    keyName: "A♭ Major\n\nF Minor",
    angle: 240,
    color: "#fd79a8",
  },
  {
    name: "E♭",
    minor: "Cm",
    keyName: "E♭ Major\n\nC Minor",
    angle: 270,
    color: "#d63031",
  },
  {
    name: "B♭",
    minor: "Gm",
    keyName: "B♭ Major\n\nG Minor",
    angle: 300,
    color: "#00cec9",
  },
  {
    name: "F",
    minor: "Dm",
    keyName: "F Major\n\nD Minor",
    angle: 330,
    color: "#ff7675",
  },
];
